{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grant.fullname" . }}-web
  labels:
    {{- include "grant.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "grant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "grant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- include "grant.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "grant.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "grant.fullname" . }}-env
          {{- with .Values.web.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.web.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.web.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        {{- with .Values.web.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
