{{- if .Values.example.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grant.fullname" . }}-example
  labels:
    {{- include "grant.labels" . | nindent 4 }}
    app.kubernetes.io/component: example
spec:
  replicas: {{ .Values.example.replicaCount }}
  selector:
    matchLabels:
      {{- include "grant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: example
  template:
    metadata:
      labels:
        {{- include "grant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: example
    spec:
      serviceAccountName: {{ include "grant.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.example.podSecurityContext | nindent 8 }}
      containers:
        - name: example
          image: "{{ .Values.example.image.repository }}:{{ .Values.example.image.tag }}"
          imagePullPolicy: {{ .Values.example.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.example.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.example.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "grant.fullname" . }}-env
          {{- with .Values.example.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.example.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.example.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.example.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.example.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.example.resources | nindent 12 }}
      volumes:
        {{- with .Values.example.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
