{{- if and .Values.api.enabled .Values.podDisruptionBudget.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "grant.fullname" . }}-api
  labels:
    {{- include "grant.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  selector:
    matchLabels:
      {{- include "grant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
