{{- if .Values.example.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grant.fullname" . }}-example
  labels:
    {{- include "grant.labels" . | nindent 4 }}
    app.kubernetes.io/component: example
spec:
  type: {{ .Values.example.service.type }}
  selector:
    {{- include "grant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: example
  ports:
    - name: http
      port: {{ .Values.example.service.port }}
      targetPort: http
{{- end }}
