/**
 * Metadata for env vars: categories, priority (main vs optional), descriptions, and dependencies.
 * Used to drive the config UI tabs and status.
 */

export type EnvCategoryId =
  | 'main'
  | 'database'
  | 'cache'
  | 'auth'
  | 'github'
  | 'security'
  | 'optional';

export interface EnvVarMeta {
  key: string;
  category: EnvCategoryId;
  /** Human-readable label */
  label: string;
  /** Short description for the UI */
  description: string;
  /** If set, this var is only relevant when the condition var has one of these values (e.g. REDIS_* when CACHE_STRATEGY=redis) */
  dependsOn?: { key: string; values: string[] };
  /** Whether this var is required for the app to work in production */
  required?: boolean;
  /** Which env file(s) this var is written to. Key = relative path from repo root. */
  envFiles: string[];
  /** If true, changing this var should sync to all listed envFiles (e.g. DB_URL in database + api) */
  syncAcrossFiles?: boolean;
  /** If set, render a selector with these options instead of a text input */
  options?: readonly string[];
  /** When options are set: open dropdown above the trigger (e.g. for fields at bottom of panel). Default is below. */
  dropdownPosition?: 'above' | 'below';
  /** If true, input only allows digits (e.g. ports) */
  digitsOnly?: boolean;
  /** If true, show a "Generate password" button below the field */
  isPassword?: boolean;
  /** If set (e.g. ','), render multiple inputs and join with this separator when persisting */
  multiValueSeparator?: string;
  /** Optional section label for grouping vars in the UI (e.g. "Rate limiting", "Row-Level Security") */
  section?: string;
  /** If true, this var is "critical" for the section: section is shown first and expanded by default; var is shown first within section */
  critical?: boolean;
}

/** Categories shown as tabs; order = display order. */
export const ENV_CATEGORIES: { id: EnvCategoryId; label: string; priority: number }[] = [
  { id: 'main', label: 'App', priority: 1 },
  { id: 'database', label: 'Database', priority: 2 },
  { id: 'cache', label: 'Cache / Redis', priority: 4 },
  { id: 'auth', label: 'Auth', priority: 5 },
  { id: 'github', label: 'GitHub OAuth', priority: 6 },
  { id: 'security', label: 'Security', priority: 7 },
  { id: 'optional', label: 'Advanced', priority: 9 },
];

/** Single source of truth: root .env only. Local dev can sync to app-level .env via scripts/env/sync-from-root.mjs */
export const ENV_FILE_PATHS = ['.env'] as const;

const META: EnvVarMeta[] = [
  // Main
  {
    key: 'DB_URL',
    category: 'main',
    label: 'Database URL',
    description: 'PostgreSQL connection string. Required for API and database package.',
    required: true,
    envFiles: ['.env'],
    syncAcrossFiles: true,
    section: 'Core',
    critical: true,
  },
  {
    key: 'APP_URL',
    category: 'main',
    label: 'App URL',
    description: 'Single public base URL for web, API, and example app (when proxied).',
    required: true,
    envFiles: ['.env'],
    section: 'Core',
    critical: true,
  },
  {
    key: 'DOCS_URL',
    category: 'main',
    label: 'Docs URL',
    description: 'Public URL of the docs site (VitePress).',
    envFiles: ['.env'],
    section: 'Core',
  },
  {
    key: 'API_PORT',
    category: 'main',
    label: 'API port',
    description: 'Port the API server listens on.',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Core',
    critical: true,
  },
  {
    key: 'SYSTEM_USER_ID',
    category: 'main',
    label: 'System user ID',
    description: 'Internal user ID for seeding; must match API config.',
    envFiles: ['.env'],
    syncAcrossFiles: true,
    section: 'Core',
    critical: true,
  },
  {
    key: 'PRIVACY_ACCOUNT_DELETION_RETENTION_DAYS',
    category: 'main',
    label: 'Account deletion retention (days)',
    description: 'Data retention period for deleted accounts (default: 30).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Privacy & retention',
  },
  {
    key: 'PRIVACY_BACKUP_RETENTION_DAYS',
    category: 'main',
    label: 'Backup retention (days)',
    description: 'Data retention period for backups (default: 90).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Privacy & retention',
  },
  // Docker
  {
    key: 'POSTGRES_DB',
    category: 'database',
    label: 'Postgres DB name',
    description: 'Database name for Docker Compose PostgreSQL.',
    envFiles: ['.env'],
    section: 'PostgreSQL',
    critical: true,
  },
  {
    key: 'POSTGRES_USER',
    category: 'database',
    label: 'Postgres user',
    description: 'Database user for Docker Compose.',
    envFiles: ['.env'],
    section: 'PostgreSQL',
    critical: true,
  },
  {
    key: 'POSTGRES_PASSWORD',
    category: 'database',
    label: 'Postgres password',
    description: 'Database password for Docker Compose.',
    envFiles: ['.env'],
    isPassword: true,
    section: 'PostgreSQL',
    critical: true,
  },
  {
    key: 'PGADMIN_EMAIL',
    category: 'database',
    label: 'PgAdmin email',
    description: 'PgAdmin login email.',
    envFiles: ['.env'],
    section: 'PgAdmin',
    critical: true,
  },
  {
    key: 'PGADMIN_PASSWORD',
    category: 'database',
    label: 'PgAdmin password',
    description: 'PgAdmin login password.',
    envFiles: ['.env'],
    isPassword: true,
    section: 'PgAdmin',
    critical: true,
  },
  // Database
  {
    key: 'DB_POOL_MAX',
    category: 'database',
    label: 'Connection pool max',
    description: 'Maximum connections in pool (default: 20).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Connection pool',
    critical: true,
  },
  {
    key: 'DB_POOL_MIN',
    category: 'database',
    label: 'Connection pool min',
    description: 'Minimum connections in pool (default: 2).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Connection pool',
  },
  {
    key: 'DB_CONNECTION_TIMEOUT',
    category: 'database',
    label: 'Connection timeout (s)',
    description: 'Connection timeout in seconds (default: 30).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Connection pool',
  },
  {
    key: 'DB_IDLE_TIMEOUT',
    category: 'database',
    label: 'Idle timeout (s)',
    description: 'Idle timeout in seconds (default: 20).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Connection pool',
  },
  {
    key: 'DB_QUERY_TIMEOUT',
    category: 'database',
    label: 'Query timeout (ms)',
    description: 'Query timeout in milliseconds (default: 60000).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Connection pool',
  },
  {
    key: 'DB_LOG_QUERIES',
    category: 'database',
    label: 'Log queries',
    description: 'Enable database query logging (default: true in development).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Connection pool',
  },
  // Auth
  {
    key: 'JWT_ACCESS_TOKEN_EXPIRATION_MINUTES',
    category: 'auth',
    label: 'Access token expiration (min)',
    description: 'Access token expiration in minutes (default: 15).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'JWT',
    critical: true,
  },
  {
    key: 'JWT_REFRESH_TOKEN_EXPIRATION_DAYS',
    category: 'auth',
    label: 'Refresh token expiration (days)',
    description: 'Refresh token expiration in days (default: 30).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'JWT',
    critical: true,
  },
  {
    key: 'JWT_JWKS_MAX_AGE_SECONDS',
    category: 'auth',
    label: 'JWKS Cache-Control max-age (s)',
    description: 'Cache-Control max-age for /.well-known/jwks.json (default: 300).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'JWT',
  },
  {
    key: 'JWT_SYSTEM_SIGNING_KEY_CACHE_TTL_SECONDS',
    category: 'auth',
    label: 'Signing key cache TTL (s)',
    description: 'TTL for cached system signing key in seconds (default: 300).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'JWT',
  },
  {
    key: 'AUTH_PROVIDER_VERIFICATION_EXPIRATION_DAYS',
    category: 'auth',
    label: 'Provider verification expiration (days)',
    description:
      'Window in days to verify email; user can resend link during this period. After this, login is blocked (default: 7).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Authentication',
    critical: true,
  },
  {
    key: 'AUTH_OTP_VALIDITY_MINUTES',
    category: 'auth',
    label: 'OTP verification token validity (min)',
    description:
      'How long each verification link/code is valid. Shown in email as "expires in X minutes" (default: 5).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Authentication',
  },
  {
    key: 'AUTH_MAX_FAILED_LOGIN_ATTEMPTS',
    category: 'auth',
    label: 'Max failed login attempts',
    description: 'Failed attempts before lockout (default: 5).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Authentication',
  },
  {
    key: 'AUTH_LOCKOUT_DURATION_MINUTES',
    category: 'auth',
    label: 'Lockout duration (min)',
    description: 'Account lockout duration in minutes (default: 15).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Authentication',
  },
  {
    key: 'AUTH_PASSWORD_RESET_OTP_VALIDITY_MINUTES',
    category: 'auth',
    label: 'Password reset OTP validity (min)',
    description: 'Password reset OTP validity in minutes (default: 60).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Authentication',
  },
  {
    key: 'TOKEN_DEFAULT_VALIDITY_MINUTES',
    category: 'auth',
    label: 'Default token validity (min)',
    description: 'Default validity for secure tokens e.g. OTP (default: 60).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Tokens',
  },
  {
    key: 'TOKEN_DEFAULT_LENGTH',
    category: 'auth',
    label: 'Default token length (bytes)',
    description: 'Default token length in bytes; hex output is 2x (default: 32).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Tokens',
  },
  {
    key: 'TOKEN_BCRYPT_ROUNDS',
    category: 'auth',
    label: 'bcrypt rounds',
    description: 'bcrypt hashing rounds for secrets (default: 10).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Tokens',
  },
  // API
  {
    key: 'CORS_DEV_ORIGINS',
    category: 'main',
    label: 'Dev CORS origins',
    description:
      'Development-only CORS origins (comma-separated). In production only frontend and additional origins apply.',
    envFiles: ['.env'],
    multiValueSeparator: ',',
    section: 'Runtime',
  },
  {
    key: 'NODE_ENV',
    category: 'main',
    label: 'Node environment',
    description: 'development | production | test (used by API and test runs).',
    envFiles: ['.env'],
    options: ['development', 'production', 'test'],
    section: 'Runtime',
  },
  {
    key: 'LOG_LEVEL',
    category: 'main',
    label: 'Log level',
    description: 'trace | debug | info | warn | error | fatal.',
    envFiles: ['.env'],
    options: ['trace', 'debug', 'info', 'warn', 'error', 'fatal'],
    dropdownPosition: 'above',
    section: 'Runtime',
  },
  {
    key: 'LOG_PRETTY_PRINT',
    category: 'main',
    label: 'Pretty-print logs',
    description: 'Pretty-print logs for readability (default: true in development).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Runtime',
  },
  // Cache
  {
    key: 'CACHE_STRATEGY',
    category: 'cache',
    label: 'Cache strategy',
    description: 'memory or redis. Use redis for multi-instance.',
    envFiles: ['.env'],
    options: ['memory', 'redis'],
    section: 'Strategy',
    critical: true,
  },
  {
    key: 'CACHE_DEFAULT_TTL',
    category: 'cache',
    label: 'Default TTL (s)',
    description: 'Default cache TTL in seconds (default: 3600).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Strategy',
  },
  {
    key: 'CACHE_MAX_SIZE',
    category: 'cache',
    label: 'Max size (bytes)',
    description: 'Max cache size in bytes for in-memory cache (default: 104857600).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Strategy',
  },
  {
    key: 'REDIS_HOST',
    category: 'cache',
    label: 'Redis host',
    description: 'Redis server host. Required when CACHE_STRATEGY=redis.',
    envFiles: ['.env'],
    dependsOn: { key: 'CACHE_STRATEGY', values: ['redis'] },
    section: 'Redis',
    critical: true,
  },
  {
    key: 'REDIS_PORT',
    category: 'cache',
    label: 'Redis port',
    description: 'Redis server port.',
    envFiles: ['.env'],
    dependsOn: { key: 'CACHE_STRATEGY', values: ['redis'] },
    digitsOnly: true,
    section: 'Redis',
    critical: true,
  },
  {
    key: 'REDIS_DB',
    category: 'cache',
    label: 'Redis DB number',
    description: 'Redis database number (default: 0).',
    envFiles: ['.env'],
    dependsOn: { key: 'CACHE_STRATEGY', values: ['redis'] },
    digitsOnly: true,
    section: 'Redis',
  },
  {
    key: 'REDIS_KEY_PREFIX',
    category: 'cache',
    label: 'Redis key prefix',
    description: 'Redis key prefix for namespacing (default: grant:).',
    envFiles: ['.env'],
    dependsOn: { key: 'CACHE_STRATEGY', values: ['redis'] },
    section: 'Redis',
  },
  {
    key: 'REDIS_CONNECTION_TIMEOUT',
    category: 'cache',
    label: 'Redis connection timeout (ms)',
    description: 'Redis connection timeout in milliseconds (default: 10000).',
    envFiles: ['.env'],
    dependsOn: { key: 'CACHE_STRATEGY', values: ['redis'] },
    digitsOnly: true,
    section: 'Redis',
  },
  {
    key: 'REDIS_ENABLE_TLS',
    category: 'cache',
    label: 'Redis TLS',
    description: 'Enable TLS for Redis (default: false).',
    envFiles: ['.env'],
    dependsOn: { key: 'CACHE_STRATEGY', values: ['redis'] },
    options: ['true', 'false'],
    section: 'Redis',
  },
  {
    key: 'REDIS_PASSWORD',
    category: 'cache',
    label: 'Redis password',
    description: 'Redis auth password (Docker Compose and API when CACHE_STRATEGY=redis).',
    envFiles: ['.env'],
    isPassword: true,
    dependsOn: { key: 'CACHE_STRATEGY', values: ['redis'] },
    section: 'Redis',
    critical: true,
  },
  // GitHub
  {
    key: 'GITHUB_CLIENT_ID',
    category: 'github',
    label: 'GitHub Client ID',
    description: 'GitHub OAuth App client ID.',
    envFiles: ['.env'],
    section: 'Credentials',
    critical: true,
  },
  {
    key: 'GITHUB_CLIENT_SECRET',
    category: 'github',
    label: 'GitHub Client Secret',
    description: 'GitHub OAuth App client secret.',
    envFiles: ['.env'],
    section: 'Credentials',
    critical: true,
  },
  {
    key: 'GITHUB_CALLBACK_URL',
    category: 'github',
    label: 'GitHub callback URL',
    description: 'Platform sign-in callback URL.',
    envFiles: ['.env'],
    section: 'Callbacks',
    critical: true,
  },
  {
    key: 'GITHUB_PROJECT_CALLBACK_URL',
    category: 'github',
    label: 'Project OAuth callback URL',
    description: 'Project app OAuth callback URL.',
    envFiles: ['.env'],
    section: 'Callbacks',
  },
  {
    key: 'GITHUB_AUTHORIZATION_URL',
    category: 'github',
    label: 'GitHub OAuth authorization URL',
    description:
      'GitHub OAuth authorization URL (default: https://github.com/login/oauth/authorize).',
    envFiles: ['.env'],
    section: 'Advanced',
  },
  {
    key: 'GITHUB_TOKEN_URL',
    category: 'github',
    label: 'GitHub OAuth token URL',
    description: 'GitHub OAuth token URL (default: https://github.com/login/oauth/access_token).',
    envFiles: ['.env'],
    section: 'Advanced',
  },
  {
    key: 'GITHUB_API_URL',
    category: 'github',
    label: 'GitHub API base URL',
    description: 'GitHub API base URL (default: https://api.github.com).',
    envFiles: ['.env'],
    section: 'Advanced',
  },
  {
    key: 'GITHUB_OAUTH_STATE_VALIDITY_MINUTES',
    category: 'github',
    label: 'OAuth state validity (min)',
    description: 'OAuth state token validity in minutes (default: 10).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Advanced',
  },
  {
    key: 'GITHUB_DEFAULT_AVATAR_URL',
    category: 'github',
    label: 'Default avatar URL',
    description: 'Default avatar URL when user has no GitHub avatar.',
    envFiles: ['.env'],
    section: 'Advanced',
  },
  {
    key: 'OAUTH_CLI_CALLBACK_TTL_SECONDS',
    category: 'github',
    label: 'CLI callback TTL (s)',
    description: 'TTL for CLI OAuth callback payloads in cache (default: 60).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Advanced',
  },
  // Security
  {
    key: 'SECURITY_FRONTEND_URL',
    category: 'security',
    label: 'Frontend URL',
    description: 'Web app URL for CORS and redirects. Required in production.',
    required: true,
    envFiles: ['.env'],
    section: 'CORS',
    critical: true,
  },
  {
    key: 'SECURITY_ADDITIONAL_ORIGINS',
    category: 'security',
    label: 'Additional CORS origins',
    description: 'Comma-separated list of allowed origins (e.g. https://app.example.com).',
    envFiles: ['.env'],
    section: 'CORS',
    critical: true,
  },
  {
    key: 'SECURITY_ENABLE_HELMET',
    category: 'security',
    label: 'Enable Helmet',
    description: 'Enable Helmet security headers (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Security headers',
    critical: true,
  },
  {
    key: 'SECURITY_ENABLE_RATE_LIMIT',
    category: 'security',
    label: 'Enable rate limiting',
    description: 'Enable rate limiting (default: true in production, false in development).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Rate limiting',
    critical: true,
  },
  {
    key: 'SECURITY_RATE_LIMIT_MAX',
    category: 'security',
    label: 'Rate limit max requests',
    description: 'Maximum requests per window (default: 100).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Rate limiting',
    critical: true,
  },
  {
    key: 'SECURITY_RATE_LIMIT_WINDOW_MINUTES',
    category: 'security',
    label: 'Rate limit window (minutes)',
    description: 'Rate limit time window in minutes (default: 15).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Rate limiting',
  },
  {
    key: 'SECURITY_RATE_LIMIT_AUTH_MAX',
    category: 'security',
    label: 'Auth rate limit max',
    description: 'Max requests per window for auth endpoints (default: 20).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Rate limiting',
  },
  {
    key: 'SECURITY_RATE_LIMIT_AUTH_WINDOW_MINUTES',
    category: 'security',
    label: 'Auth rate limit window (minutes)',
    description: 'Auth rate limit time window in minutes (default: 15).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Rate limiting',
  },
  {
    key: 'SECURITY_RATE_LIMIT_PER_TENANT_ENABLED',
    category: 'security',
    label: 'Per-tenant rate limiting',
    description: 'Limit requests per tenant (noisy neighbor protection). Default: false.',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Rate limiting',
  },
  {
    key: 'SECURITY_RATE_LIMIT_PER_TENANT_MAX',
    category: 'security',
    label: 'Per-tenant rate limit max',
    description: 'Max requests per window per tenant (default: 200).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Rate limiting',
  },
  {
    key: 'SECURITY_RATE_LIMIT_PER_TENANT_WINDOW_MINUTES',
    category: 'security',
    label: 'Per-tenant rate limit window (minutes)',
    description: 'Per-tenant rate limit time window in minutes (default: 15).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Rate limiting',
  },
  {
    key: 'SECURITY_API_KEY',
    category: 'security',
    label: 'API key',
    description: 'Optional API key for external service authentication.',
    envFiles: ['.env'],
    section: 'API key',
  },
  {
    key: 'SECURITY_ENABLE_RLS',
    category: 'security',
    label: 'Enable RLS',
    description: 'Enable database Row-Level Security for scoped requests.',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Row-Level Security',
    critical: true,
  },
  {
    key: 'SECURITY_RLS_ROLE',
    category: 'security',
    label: 'RLS role name',
    description:
      'RLS restricted role; must match role in DB migration (default: grant_app_restricted).',
    envFiles: ['.env'],
    section: 'Row-Level Security',
  },
  // Optional
  {
    key: 'METRICS_ENABLED',
    category: 'optional',
    label: 'Enable Prometheus metrics',
    description: 'Enable Prometheus metrics collection (default: false).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Metrics',
  },
  {
    key: 'METRICS_ENDPOINT',
    category: 'optional',
    label: 'Metrics HTTP path',
    description: 'Metrics HTTP path (default: /metrics).',
    envFiles: ['.env'],
    section: 'Metrics',
  },
  {
    key: 'METRICS_COLLECT_DEFAULTS',
    category: 'optional',
    label: 'Collect default metrics',
    description: 'Collect default metrics e.g. CPU, memory (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Metrics',
  },
  {
    key: 'GRAFANA_ADMIN_PASSWORD',
    category: 'optional',
    label: 'Grafana admin password',
    description:
      'Grafana dashboard login (http://localhost:3001). Add Prometheus (and optionally Jaeger) as data sources in Grafana to view metrics and traces.',
    envFiles: ['.env'],
    isPassword: true,
    section: 'Metrics',
  },
  {
    key: 'TELEMETRY_PROVIDER',
    category: 'optional',
    label: 'Telemetry provider',
    description: 'Provider: none | cloudwatch (default: none).',
    envFiles: ['.env'],
    options: ['none', 'cloudwatch'],
    section: 'Telemetry',
  },
  {
    key: 'TELEMETRY_CLOUDWATCH_REGION',
    category: 'optional',
    label: 'CloudWatch region',
    description: 'AWS region for CloudWatch (when provider=cloudwatch).',
    envFiles: ['.env'],
    dependsOn: { key: 'TELEMETRY_PROVIDER', values: ['cloudwatch'] },
    section: 'Telemetry',
  },
  {
    key: 'TELEMETRY_CLOUDWATCH_LOG_GROUP',
    category: 'optional',
    label: 'CloudWatch log group',
    description: 'CloudWatch log group name.',
    envFiles: ['.env'],
    dependsOn: { key: 'TELEMETRY_PROVIDER', values: ['cloudwatch'] },
    section: 'Telemetry',
  },
  {
    key: 'TELEMETRY_CLOUDWATCH_LOG_STREAM_PREFIX',
    category: 'optional',
    label: 'CloudWatch log stream prefix',
    description: 'CloudWatch log stream prefix (default: grant-api).',
    envFiles: ['.env'],
    dependsOn: { key: 'TELEMETRY_PROVIDER', values: ['cloudwatch'] },
    section: 'Telemetry',
  },
  {
    key: 'ANALYTICS_ENABLED',
    category: 'optional',
    label: 'Enable analytics',
    description: 'Enable analytics (default: false).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Analytics',
  },
  {
    key: 'ANALYTICS_PROVIDER',
    category: 'optional',
    label: 'Analytics provider',
    description: 'Provider: none | umami (default: none).',
    envFiles: ['.env'],
    options: ['none', 'umami'],
    section: 'Analytics',
  },
  {
    key: 'ANALYTICS_UMAMI_API_URL',
    category: 'optional',
    label: 'Umami API URL',
    description: 'Umami API URL (when provider=umami).',
    envFiles: ['.env'],
    dependsOn: { key: 'ANALYTICS_PROVIDER', values: ['umami'] },
    section: 'Analytics',
  },
  {
    key: 'ANALYTICS_UMAMI_WEBSITE_ID',
    category: 'optional',
    label: 'Umami website ID',
    description: 'Umami website ID.',
    envFiles: ['.env'],
    dependsOn: { key: 'ANALYTICS_PROVIDER', values: ['umami'] },
    section: 'Analytics',
  },
  {
    key: 'ANALYTICS_UMAMI_HOSTNAME',
    category: 'optional',
    label: 'Umami hostname',
    description: 'Umami hostname (default: grant-api).',
    envFiles: ['.env'],
    dependsOn: { key: 'ANALYTICS_PROVIDER', values: ['umami'] },
    section: 'Analytics',
  },
  {
    key: 'UMAMI_DB_PASSWORD',
    category: 'optional',
    label: 'Umami DB password',
    description: 'Umami Postgres password (used by umami-db and umami app).',
    envFiles: ['.env'],
    isPassword: true,
    section: 'Analytics',
  },
  {
    key: 'UMAMI_APP_SECRET',
    category: 'optional',
    label: 'Umami app secret',
    description: 'Umami app secret; use a random string in production.',
    envFiles: ['.env'],
    isPassword: true,
    section: 'Analytics',
  },
  {
    key: 'TRACING_ENABLED',
    category: 'optional',
    label: 'Enable tracing',
    description: 'Enable OpenTelemetry tracing (default: false).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Tracing',
  },
  {
    key: 'TRACING_BACKEND',
    category: 'optional',
    label: 'Tracing backend',
    description: 'Tracing backend: jaeger | otlp (default: jaeger).',
    envFiles: ['.env'],
    options: ['jaeger', 'otlp'],
    section: 'Tracing',
  },
  {
    key: 'JAEGER_ENDPOINT',
    category: 'optional',
    label: 'Jaeger endpoint',
    description: 'Jaeger collector endpoint (when backend=jaeger).',
    envFiles: ['.env'],
    dependsOn: { key: 'TRACING_ENABLED', values: ['true'] },
    section: 'Tracing',
  },
  {
    key: 'OTLP_ENDPOINT',
    category: 'optional',
    label: 'OTLP endpoint',
    description: 'OTLP collector endpoint (when backend=otlp).',
    envFiles: ['.env'],
    dependsOn: { key: 'TRACING_ENABLED', values: ['true'] },
    section: 'Tracing',
  },
  {
    key: 'TRACING_SAMPLING_RATE',
    category: 'optional',
    label: 'Sampling rate',
    description: 'Tracing sampling rate 0–1 (default: 1.0).',
    envFiles: ['.env'],
    section: 'Tracing',
  },
  {
    key: 'TRACING_SERVICE_NAME',
    category: 'optional',
    label: 'Service name',
    description: 'Tracing service name (default: grant-api).',
    envFiles: ['.env'],
    section: 'Tracing',
  },
  {
    key: 'COLLECTOR_OTLP_ENABLED',
    category: 'optional',
    label: 'Jaeger OTLP enabled',
    description: 'Enable OTLP receiver for trace ingestion (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Tracing',
  },
  {
    key: 'APOLLO_INTROSPECTION',
    category: 'optional',
    label: 'GraphQL introspection',
    description: 'Enable GraphQL introspection (default: true in development).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'GraphQL',
  },
  {
    key: 'APOLLO_PLAYGROUND',
    category: 'optional',
    label: 'GraphQL playground',
    description: 'Enable GraphQL playground (default: true in development).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'GraphQL',
  },
  {
    key: 'APOLLO_INCLUDE_STACKTRACE',
    category: 'optional',
    label: 'Include stack traces in errors',
    description: 'Include stack traces in GraphQL errors (default: true in development).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'GraphQL',
  },
  {
    key: 'SWAGGER_ENABLED',
    category: 'optional',
    label: 'Enable Swagger UI',
    description: 'Enable Swagger UI at /api-docs (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_SITE_TITLE',
    category: 'optional',
    label: 'Swagger site title',
    description: 'Swagger UI site title (default: Grant API Docs).',
    envFiles: ['.env'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_PERSIST_AUTHORIZATION',
    category: 'optional',
    label: 'Persist authorization',
    description: 'Persist authorization between page refreshes (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_DISPLAY_REQUEST_DURATION',
    category: 'optional',
    label: 'Display request duration',
    description: 'Display request duration in responses (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_FILTER',
    category: 'optional',
    label: 'Enable filter/search',
    description: 'Enable filter/search in operations (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_TRY_IT_OUT_ENABLED',
    category: 'optional',
    label: 'Try it out by default',
    description: 'Enable Try it out by default (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_MODELS_EXPAND_DEPTH',
    category: 'optional',
    label: 'Models expand depth',
    description: 'Depth to expand models/schemas (default: 3).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_MODEL_EXPAND_DEPTH',
    category: 'optional',
    label: 'Model expand depth',
    description: 'Depth to expand individual model properties (default: 3).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_DOC_EXPANSION',
    category: 'optional',
    label: 'Doc expansion',
    description: 'Documentation expansion: list | full | none (default: list).',
    envFiles: ['.env'],
    options: ['list', 'full', 'none'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_DEEP_LINKING',
    category: 'optional',
    label: 'Deep linking',
    description: 'Enable deep linking for sharing (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_DISPLAY_OPERATION_ID',
    category: 'optional',
    label: 'Display operation ID',
    description: 'Display operation IDs (default: false).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_SYNTAX_THEME',
    category: 'optional',
    label: 'Syntax theme',
    description: 'Syntax highlighting theme (default: monokai).',
    envFiles: ['.env'],
    options: ['agate', 'arta', 'monokai', 'nord', 'obsidian', 'tomorrow-night'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_SHOW_EXTENSIONS',
    category: 'optional',
    label: 'Show extensions',
    description: 'Show extensions (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'SWAGGER_SHOW_COMMON_EXTENSIONS',
    category: 'optional',
    label: 'Show common extensions',
    description: 'Show common extensions (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'OPENAPI_PRODUCTION_URL',
    category: 'optional',
    label: 'Production URL (OpenAPI doc)',
    description:
      'Production server URL shown in OpenAPI document in dev (default: https://api.grant.center).',
    envFiles: ['.env'],
    section: 'Swagger / OpenAPI',
  },
  {
    key: 'I18N_DEFAULT_LOCALE',
    category: 'main',
    label: 'Default locale',
    description: 'Default locale; must be a supported locale (default: en).',
    envFiles: ['.env'],
    section: 'Internationalization',
    options: ['en', 'de'],
  },
  {
    key: 'I18N_DEBUG',
    category: 'main',
    label: 'i18n debug mode',
    description: 'Enable i18n debug mode (default: true in development).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Internationalization',
  },
  {
    key: 'EMAIL_PROVIDER',
    category: 'main',
    label: 'Email provider',
    description: 'Provider: console | mailgun | mailjet | ses | smtp.',
    envFiles: ['.env'],
    options: ['console', 'mailgun', 'mailjet', 'ses', 'smtp'],
    section: 'Email',
  },
  {
    key: 'EMAIL_FROM',
    category: 'main',
    label: 'From email',
    description: 'From email address. Required for sending email.',
    envFiles: ['.env'],
    section: 'Email',
  },
  {
    key: 'EMAIL_FROM_NAME',
    category: 'main',
    label: 'From name',
    description: 'From name displayed in emails (optional).',
    envFiles: ['.env'],
    section: 'Email',
  },
  {
    key: 'MAILGUN_API_KEY',
    category: 'main',
    label: 'Mailgun API key',
    description: 'Mailgun API key (when provider=mailgun).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['mailgun'] },
    section: 'Email',
  },
  {
    key: 'MAILGUN_DOMAIN',
    category: 'main',
    label: 'Mailgun domain',
    description: 'Mailgun domain (when provider=mailgun).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['mailgun'] },
    section: 'Email',
  },
  {
    key: 'MAILJET_API_KEY',
    category: 'main',
    label: 'Mailjet API key',
    description: 'Mailjet API key (when provider=mailjet).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['mailjet'] },
    section: 'Email',
  },
  {
    key: 'MAILJET_SECRET_KEY',
    category: 'main',
    label: 'Mailjet secret key',
    description: 'Mailjet secret key (when provider=mailjet).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['mailjet'] },
    section: 'Email',
  },
  {
    key: 'SMTP_HOST',
    category: 'main',
    label: 'SMTP host',
    description: 'SMTP server hostname (when provider=smtp).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['smtp'] },
    section: 'Email',
  },
  {
    key: 'SMTP_PORT',
    category: 'main',
    label: 'SMTP port',
    description: 'SMTP server port (25, 465, or 587).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['smtp'] },
    digitsOnly: true,
    section: 'Email',
  },
  {
    key: 'SMTP_USER',
    category: 'main',
    label: 'SMTP username',
    description: 'SMTP username (when provider=smtp).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['smtp'] },
    section: 'Email',
  },
  {
    key: 'SMTP_PASSWORD',
    category: 'main',
    label: 'SMTP password',
    description: 'SMTP password (when provider=smtp).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['smtp'] },
    isPassword: true,
    section: 'Email',
  },
  {
    key: 'SMTP_SECURE',
    category: 'main',
    label: 'SMTP secure',
    description: 'Use TLS/SSL for SMTP (default: true for port 465).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['smtp'] },
    options: ['true', 'false'],
    section: 'Email',
  },
  {
    key: 'EMAIL_SES_CLIENT_ID',
    category: 'main',
    label: 'SES access key ID',
    description: 'AWS SES Access Key ID (when provider=ses).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['ses'] },
    section: 'Email',
  },
  {
    key: 'EMAIL_SES_CLIENT_SECRET',
    category: 'main',
    label: 'SES secret access key',
    description: 'AWS SES Secret Access Key (when provider=ses).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['ses'] },
    isPassword: true,
    section: 'Email',
  },
  {
    key: 'EMAIL_SES_REGION',
    category: 'main',
    label: 'SES region',
    description: 'AWS region for SES (default: us-east-1).',
    envFiles: ['.env'],
    dependsOn: { key: 'EMAIL_PROVIDER', values: ['ses'] },
    section: 'Email',
  },
  {
    key: 'STORAGE_PROVIDER',
    category: 'main',
    label: 'Storage provider',
    description: 'Provider: local | s3.',
    envFiles: ['.env'],
    options: ['local', 's3'],
    section: 'File Storage',
  },
  {
    key: 'STORAGE_UPLOAD_MAX_FILE_SIZE',
    category: 'main',
    label: 'Max upload size (bytes)',
    description: 'Maximum file size for uploads in bytes (default: 5242880).',
    envFiles: ['.env'],
    digitsOnly: true,
    section: 'File Storage',
  },
  {
    key: 'STORAGE_LOCAL_BASE_PATH',
    category: 'main',
    label: 'Local base path',
    description: 'Base path for local file storage (default: ./storage).',
    envFiles: ['.env'],
    dependsOn: { key: 'STORAGE_PROVIDER', values: ['local'] },
    section: 'File Storage',
  },
  {
    key: 'STORAGE_S3_BUCKET',
    category: 'main',
    label: 'S3 bucket',
    description: 'S3 bucket name (when provider=s3).',
    envFiles: ['.env'],
    dependsOn: { key: 'STORAGE_PROVIDER', values: ['s3'] },
    section: 'File Storage',
  },
  {
    key: 'STORAGE_S3_REGION',
    category: 'main',
    label: 'S3 region',
    description: 'AWS region for S3 (default: us-east-1).',
    envFiles: ['.env'],
    dependsOn: { key: 'STORAGE_PROVIDER', values: ['s3'] },
    section: 'File Storage',
  },
  {
    key: 'STORAGE_S3_ACCESS_KEY_ID',
    category: 'main',
    label: 'S3 access key ID',
    description: 'AWS access key ID (when provider=s3).',
    envFiles: ['.env'],
    dependsOn: { key: 'STORAGE_PROVIDER', values: ['s3'] },
    section: 'File Storage',
  },
  {
    key: 'STORAGE_S3_SECRET_ACCESS_KEY',
    category: 'main',
    label: 'S3 secret access key',
    description: 'AWS secret access key (when provider=s3).',
    envFiles: ['.env'],
    dependsOn: { key: 'STORAGE_PROVIDER', values: ['s3'] },
    isPassword: true,
    section: 'File Storage',
  },
  {
    key: 'STORAGE_S3_ENDPOINT',
    category: 'main',
    label: 'S3 endpoint',
    description: 'Custom S3 endpoint (optional, e.g. MinIO).',
    envFiles: ['.env'],
    dependsOn: { key: 'STORAGE_PROVIDER', values: ['s3'] },
    section: 'File Storage',
  },
  {
    key: 'STORAGE_S3_PUBLIC_URL',
    category: 'main',
    label: 'S3 public URL',
    description: 'Public URL base (e.g. CloudFront).',
    envFiles: ['.env'],
    dependsOn: { key: 'STORAGE_PROVIDER', values: ['s3'] },
    section: 'File Storage',
  },
  {
    key: 'DEMO_MODE_ENABLED',
    category: 'main',
    label: 'Demo mode enabled',
    description:
      'Enable demo mode for limited-usage deployments. When enabled, the demo database can be reset and reseeded on a schedule.',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Demo mode',
  },
  {
    key: 'DEMO_MODE_DB_REFRESH_SCHEDULE',
    category: 'main',
    label: 'Demo DB refresh cron',
    description:
      'Cron pattern for automatic demo database refresh (default: 0 0 */2 * * = every 2 days at midnight).',
    envFiles: ['.env'],
    section: 'Demo mode',
  },
  {
    key: 'JOBS_ENABLED',
    category: 'main',
    label: 'Enable job scheduling',
    description: 'Enable job scheduling (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Jobs',
  },
  {
    key: 'JOBS_PROVIDER',
    category: 'main',
    label: 'Job provider',
    description: 'Provider: node-cron | bullmq (BullMQ requires Redis).',
    envFiles: ['.env'],
    options: ['node-cron', 'bullmq'],
    section: 'Jobs',
  },
  {
    key: 'JOBS_DATA_RETENTION_SCHEDULE',
    category: 'main',
    label: 'Data retention cron',
    description: 'Cron pattern for data retention cleanup (default: 0 2 * * *).',
    envFiles: ['.env'],
    section: 'Jobs',
  },
  {
    key: 'JOBS_DATA_RETENTION_ENABLED',
    category: 'main',
    label: 'Data retention job enabled',
    description: 'Enable data retention cleanup job (default: true).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Jobs',
  },
  {
    key: 'JOBS_SYSTEM_SIGNING_KEY_ROTATION_SCHEDULE',
    category: 'main',
    label: 'Signing key rotation cron',
    description: 'Cron for system signing key rotation (default: 0 0 1 * *).',
    envFiles: ['.env'],
    section: 'Jobs',
  },
  {
    key: 'JOBS_SYSTEM_SIGNING_KEY_ROTATION_ENABLED',
    category: 'main',
    label: 'Signing key rotation enabled',
    description: 'Enable automatic signing key rotation (default: false).',
    envFiles: ['.env'],
    options: ['true', 'false'],
    section: 'Jobs',
  },
  {
    key: 'JOBS_BULLMQ_ATTEMPTS',
    category: 'main',
    label: 'BullMQ retry attempts',
    description: 'Retry attempts for failed jobs (default: 3).',
    envFiles: ['.env'],
    dependsOn: { key: 'JOBS_PROVIDER', values: ['bullmq'] },
    digitsOnly: true,
    section: 'Jobs',
  },
  {
    key: 'JOBS_BULLMQ_BACKOFF_TYPE',
    category: 'main',
    label: 'BullMQ backoff type',
    description: 'Backoff type: exponential | fixed (default: exponential).',
    envFiles: ['.env'],
    dependsOn: { key: 'JOBS_PROVIDER', values: ['bullmq'] },
    options: ['exponential', 'fixed'],
    section: 'Jobs',
  },
  {
    key: 'JOBS_BULLMQ_BACKOFF_DELAY',
    category: 'main',
    label: 'BullMQ backoff delay (ms)',
    description: 'Backoff delay in ms before retry (default: 2000).',
    envFiles: ['.env'],
    dependsOn: { key: 'JOBS_PROVIDER', values: ['bullmq'] },
    digitsOnly: true,
    section: 'Jobs',
  },
  {
    key: 'JOBS_BULLMQ_REMOVE_ON_COMPLETE_AGE',
    category: 'main',
    label: 'BullMQ remove on complete (s)',
    description: 'Completed job retention age in seconds (default: 604800).',
    envFiles: ['.env'],
    dependsOn: { key: 'JOBS_PROVIDER', values: ['bullmq'] },
    digitsOnly: true,
    section: 'Jobs',
  },
  {
    key: 'JOBS_BULLMQ_REMOVE_ON_FAIL_AGE',
    category: 'main',
    label: 'BullMQ remove on fail (s)',
    description: 'Failed job retention age in seconds (default: 2592000).',
    envFiles: ['.env'],
    dependsOn: { key: 'JOBS_PROVIDER', values: ['bullmq'] },
    digitsOnly: true,
    section: 'Jobs',
  },
  {
    key: 'NEXT_PUBLIC_ACCOUNT_DELETION_RETENTION_DAYS',
    category: 'optional',
    label: 'Account deletion retention (days)',
    description:
      'Shown in the web app (e.g. privacy settings). Replicated from API PRIVACY_ACCOUNT_DELETION_RETENTION_DAYS when set in config.',
    envFiles: ['.env'],
    digitsOnly: true,
  },
];

const META_BY_KEY = new Map(META.map((m) => [m.key, m]));

export function getEnvVarMeta(key: string): EnvVarMeta | undefined {
  return META_BY_KEY.get(key);
}

export function getAllEnvVarMeta(): EnvVarMeta[] {
  return [...META];
}

export function getMetaByCategory(category: EnvCategoryId): EnvVarMeta[] {
  return META.filter((m) => m.category === category);
}

export function getSyncTargetsForKey(key: string): string[] {
  const meta = getEnvVarMeta(key);
  return meta?.envFiles ?? ['.env'];
}
