import { describe, expect, it } from 'vitest';

import { generateTypesContent, toPascalCase } from './generate-types-impl.js';

describe('toPascalCase', () => {
  it('converts kebab-case to PascalCase', () => {
    expect(toPascalCase('user-documents')).toBe('UserDocuments');
    expect(toPascalCase('my-resource')).toBe('MyResource');
  });

  it('converts single word (lowercase) to PascalCase', () => {
    expect(toPascalCase('document')).toBe('Document');
  });

  it('handles already PascalCase action names', () => {
    expect(toPascalCase('Create')).toBe('Create');
    expect(toPascalCase('Read')).toBe('Read');
  });

  it('splits on hyphens, underscores, colons, dots, spaces', () => {
    expect(toPascalCase('user_documents')).toBe('UserDocuments');
    expect(toPascalCase('user.documents')).toBe('UserDocuments');
    expect(toPascalCase('user documents')).toBe('UserDocuments');
  });

  it('returns empty string for empty input', () => {
    expect(toPascalCase('')).toBe('');
  });
});

describe('generateTypesContent', () => {
  it('generates ResourceSlug and ResourceAction with slugs and actions', () => {
    const slugs = ['document', 'report', 'user-documents'];
    const actions = ['Create', 'Read', 'Update', 'Delete'];
    const content = generateTypesContent(slugs, actions);

    expect(content).toContain('// Generated by Grant CLI (grant generate-types)');
    expect(content).toContain('export const ResourceSlug = {');
    expect(content).toContain('Document: "document"');
    expect(content).toContain('Report: "report"');
    expect(content).toContain('UserDocuments: "user-documents"');
    expect(content).toContain(
      'export type ResourceSlug = (typeof ResourceSlug)[keyof typeof ResourceSlug]'
    );

    expect(content).toContain('export const ResourceAction = {');
    expect(content).toContain('Create: "Create"');
    expect(content).toContain('Read: "Read"');
    expect(content).toContain(
      'export type ResourceAction = (typeof ResourceAction)[keyof typeof ResourceAction]'
    );
  });

  it('deduplicates and sorts slugs and actions', () => {
    const content = generateTypesContent(
      ['report', 'document', 'document'],
      ['Read', 'Create', 'Read']
    );
    expect(content).toContain('Document: "document"');
    expect(content).toContain('Report: "report"');
    const docPos = content.indexOf('Document:');
    const reportPos = content.indexOf('Report:');
    expect(docPos).toBeLessThan(reportPos);
  });

  it('handles empty arrays', () => {
    const content = generateTypesContent([], []);
    expect(content).toContain('export const ResourceSlug = {');
    expect(content).toContain('} as const;');
    expect(content).toContain('export const ResourceAction = {');
  });
});
